version: '3'
services:
    database:
        image: mariadb:latest
        restart: always
        volumes:
            - ./db:/docker-entrypoint-initdb.d

        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: cod_vuejs
    cod-app:
        build: 
            context: .
            dockerfile: Dockerfile
        image: gtel-dev/cod
        restart: always
        volumes:
            - .:/var/www/html
        ports:
            - 8000:8000
        depends_on:
            - database
        command:  sh -c "php artisan migrate && php artisan serve --host=0.0.0.0"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - database
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            PMA_USER: root
            PMA_PASSWORD: root
        restart: always
        ports:
            - 8081:80


